export enum TypPowiadomienia {
  ZLECONO_TRANSPORT_PRZESYLKI = 'ZLECONO_TRANSPORT_PRZESYLKI',
  ZMIANA_STATUSU_ZLECENIA = 'ZMIANA_STATUSU_ZLECENIA',
  WYSTAW_OCENE_ZLECENIODAWCY = 'WYSTAW_OCENE_ZLECENIODAWCY',
  WYSTAW_OCENE_ZLECENIOBIORCY = 'WYSTAW_OCENE_ZLECENIOBIORCY'
}
